### ISSUE TITLE
how are irc and irc2 different ?

### ISSUE THREAD

**Issue by bapungiri** [flatironinstitute/ironclust#43]
Just wanted to know how are they different ? irc2 does not seem to support .dat file.

**Comment by jamesjun** [comment]
irc2 is more scalable (up to a terabyte-size recording) because it uses
disk caching to reduce memory use and a sliding-window (~2560s window)
clustering algorithm. I am adding support for .dat format from INTAN and
Neurosuite format. You need to have either ".xml" (Neurosuite) or
"info.rhd" for INTAN format. I will update the instruction on README.md

-James
